"""
llmtest CLI entry point.

Usage:
    llmtest run tests/          # Run all LLM tests
    llmtest run tests/ --json   # JSON output for CI
    llmtest run tests/ --junit  # JUnit XML for CI
    llmtest init                # Create a starter test file
    llmtest providers           # List available providers
"""

from __future__ import annotations

import argparse
import os
import sys


def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="llmtest",
        description="The pytest for LLMs — test your AI outputs like you test your code.",
    )
    parser.add_argument("--version", action="store_true", help="Show version")

    subparsers = parser.add_subparsers(dest="command")

    # run command
    run_parser = subparsers.add_parser("run", help="Run LLM tests")
    run_parser.add_argument("path", nargs="?", default=".", help="Test file or directory")
    run_parser.add_argument("--provider", "-p", default=None, help="LLM provider to use")
    run_parser.add_argument("--model", "-m", default=None, help="Model name")
    run_parser.add_argument("--json", action="store_true", help="Output results as JSON")
    run_parser.add_argument("--junit", metavar="FILE", help="Write JUnit XML to file")
    run_parser.add_argument("--max-concurrent", type=int, default=10, help="Max parallel LLM calls")
    run_parser.add_argument(
        "--timeout", type=float, default=30.0, help="Per-test timeout in seconds"
    )
    run_parser.add_argument(
        "--fail-fast", action="store_true", help="Stop on first critical failure"
    )
    run_parser.add_argument("--dry-run", action="store_true", help="Validate without calling LLMs")
    run_parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")

    # init command
    init_parser = subparsers.add_parser("init", help="Create a starter test file")
    init_parser.add_argument("--dir", default=".", help="Directory to create test file in")

    # providers command
    subparsers.add_parser("providers", help="List available LLM providers")

    return parser


def cmd_run(args: argparse.Namespace) -> int:
    """Run LLM tests via pytest."""
    pytest_args = [args.path, "-v", "--tb=short", "-m", "llmtest"]

    if args.fail_fast:
        pytest_args.append("-x")

    if args.verbose:
        pytest_args.append("-s")

    try:
        import pytest

        return pytest.main(pytest_args)
    except ImportError:
        print("Error: pytest not installed. Run: pip install pytest")
        return 1


def cmd_init(args: argparse.Namespace) -> int:
    """Create a starter test file."""
    target_dir = args.dir
    test_file = os.path.join(target_dir, "test_llm.py")

    if os.path.exists(test_file):
        print(f"File already exists: {test_file}")
        return 1

    content = '''"""LLM tests — generated by `llmtest init`."""
from llmtest import expect, llm_test


@llm_test(
    expect.is_not_empty(),
    expect.latency_under(5000),
    expect.cost_under(0.01),
)
def test_basic_response(llm):
    """Verify the LLM returns a non-empty response."""
    return llm("Say hello in one sentence.")


@llm_test(
    expect.contains("Paris"),
    expect.latency_under(3000),
)
def test_factual_accuracy(llm):
    """Verify the LLM knows basic facts."""
    return llm("What is the capital of France? Answer in one word.")


@llm_test(
    expect.valid_json(),
    expect.cost_under(0.01),
)
def test_json_output(llm):
    """Verify the LLM can produce valid JSON."""
    return llm("Return a JSON object with keys 'name' and 'age'. Only output JSON, nothing else.")
'''
    os.makedirs(target_dir, exist_ok=True)
    with open(test_file, "w") as f:
        f.write(content)

    print(f"Created {test_file}")
    print(f"Run your tests with: pytest {test_file} -v")
    return 0


def cmd_providers(args: argparse.Namespace) -> int:
    """List available LLM providers."""
    from llmtest_core.providers import ProviderRegistry

    # Try to load plugins
    try:
        ProviderRegistry.load_plugins()
    except Exception:
        pass

    providers = ProviderRegistry.available()

    if not providers:
        print("No providers found.")
        print("Install a provider: pip install pytest-llmtest[openai]")
        return 0

    print("Available LLM providers:")
    for name in sorted(providers):
        provider = ProviderRegistry.get(name)
        print(f"  - {name} ({type(provider).__name__})")

    return 0


def app() -> None:
    """Main CLI entry point."""
    parser = create_parser()
    args = parser.parse_args()

    if args.version:
        from llmtest_core import __version__

        print(f"llmtest {__version__}")
        sys.exit(0)

    if args.command is None:
        parser.print_help()
        sys.exit(0)

    commands = {
        "run": cmd_run,
        "init": cmd_init,
        "providers": cmd_providers,
    }

    handler = commands.get(args.command)
    if handler:
        sys.exit(handler(args))
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    app()
